import { useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Loader2 } from "lucide-react";

const SessionStart = () => {
  const { quizId } = useParams();
  const navigate = useNavigate();
  const { toast } = useToast();

  useEffect(() => {
    createSession();
  }, [quizId]);

  const createSession = async () => {
    if (!quizId) {
      navigate("/dashboard");
      return;
    }

    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        navigate("/auth");
        return;
      }

      // Create a new session (session_code will be auto-generated by database trigger)
      const { data: session, error } = await supabase
        .from('sessions')
        .insert([{
          quiz_id: quizId,
          created_by: user.id,
          status: 'waiting',
          session_code: '', // Will be auto-generated by trigger
        }])
        .select()
        .single();

      if (error) throw error;

      // Redirect to the presenter control panel
      navigate(`/session/${session.id}/present`);
    } catch (error: any) {
      console.error('Session creation error:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to create session",
        variant: "destructive",
      });
      navigate("/dashboard");
    }
  };

  return (
    <div className="min-h-screen bg-gradient-subtle flex items-center justify-center">
      <div className="text-center">
        <Loader2 className="w-12 h-12 animate-spin mx-auto mb-4 text-primary" />
        <h2 className="text-2xl font-bold mb-2">Creating Session...</h2>
        <p className="text-muted-foreground">Generating your unique session code</p>
      </div>
    </div>
  );
};

export default SessionStart;
